### ISSUE TITLE
Add Ancillary file upload to API

### ISSUE THREAD

**Issue by maxinelasp** [IMAP-Science-Operations-Center/sds-data-manager#282]
### Summary

Ancillary files or calibration files are [additional files with special rules](https://imap-processing.readthedocs.io/en/latest/data-access-api/calibration-files.html). The API should be able to accept these as valid uploads and put them in instrument-specific folders. 

This would be a good ticket for a student interested in CDK and AWS work.

### Requirements

The more specific the better.
  - [ ] Meet the naming requirements laid out in the [ancillary files](https://imap-processing.readthedocs.io/en/latest/data-access-api/calibration-files.html) page
  - [ ] Put the ancillary files in instrument specific areas in the S3 bucket
  - [ ] API should accept ancillary files that match the naming conventions, are not duplicated, and place them in the correct subfolder.

**Comment by greglucas** [comment]
This would be great to prioritize if possible. Do we need additional details added here? I actually think that this one is blocked by https://github.com/IMAP-Science-Operations-Center/imap-data-access/issues/39 because the `imap-data-access` is what validates/verifies the files and I think we utilize that in the AWS resources (not the other way around).

So (1) should be to add a `class AncillaryFiles`, similar to `SPICEFiles` and `ScienceFiles`. Following the naming conventions outlined in that document @maxinelasp linked to. (2) is to utilize those `AncillaryFiles` to place them within s3 and allow for upload.

**Comment by daralynnrhode** [comment]
@greglucas Sounds good! This is on my radar and will be the next task I tackle once I finish the data validation. For reference, I am about done with that and just working on implementing some tests.

**Comment by greglucas** [comment]
This was completed in `imap-data-access` and included here now.
