### ISSUE TITLE
Transition the dependency database to a lambda + file system

### ISSUE THREAD

**Issue by maxinelasp** [IMAP-Science-Operations-Center/sds-data-manager#359]
### Summary

Our current system uses a file, which populates a database table, which then contains dependency information (upstream + downstream). However, the file and table often get misaligned and cause issues. 

Instead, we should create a lambda that stores the file and can be accessed via API calls to replace the database. This will allow us to keep the file and the retrieval process closely connected, be able to deploy changes in the dependencies without needing to redeploy anything else, and ensure that the file is the one source of truth for access. Putting the code in a lambda also gives us flexibility to add additional features as needed for reprocessing, spice, etc.

### Requirements

The more specific the better.
  - [x] Create a lambda which uses the dependencies csv file to return the dependencies of a requested instrument and level.
  - [ ] Update the existing lambdas that use the dependency table to retrieve information from the lambda instead
  - [ ] Remove the dependency table and create_schema lambda
  - [ ] Ensure that we can deploy only one lambda when the file changes (CDK should do this automatically, as long as there are no CDK dependencies between anything else)

### Related tickets

should make #299 not necessary
Related PRs:
#352 
#351

**Comment by maxinelasp** [comment]
Closed with #499
